const imageBase = `${import.meta.env.BASE_URL}assets`;

export const stays = [
  {
    name: 'CVK Park Bosphorus Hotel Istanbul',
    image: `${imageBase}/listing-bg-main.svg`,
    imagesCount: 9,
    location: 'Gümüssuyu Mah. Inönü Cad. No:8, Istanbul 34437',
    rating: 4.2,
    stars: 5,
    amenities: '20',
    price: 513,
    currency: '$',
    per: '/night',
    tax: 'incl. tax',
    reviews: 54,
    reviewLabel: 'Very Good',
  },
  {
    name: 'Eresin Hotels Sultanahmet - Boutique Class',
    image: `${imageBase}/listing-bg-main-2.jpg`,
    imagesCount: 9,
    location: 'Kucukayasofya No. 40 Sultanahmet, Istanbul 34022',
    rating: 4.2,
    stars: 5,
    amenities: '20',
    price: 290,
    currency: '$',
    per: '/night',
    tax: 'excl. tax',
    reviews: 54,
    reviewLabel: 'Very Good',
  },
  {
    name: 'CVK Park Bosphorus Hotel Istanbul',
    image: `${imageBase}/listing-bg-4.jpg`,
    imagesCount: 9,
    location: 'Gümüssuyu Mah. Inönü Cad. No:8, Istanbul 34437',
    rating: 4.2,
    stars: 5,
    amenities: '20',
    price: 290,
    currency: '$',
    per: '/night',
    tax: 'incl. tax',
    reviews: 54,
    reviewLabel: 'Very Good',
  },
  {
    name: 'Eresin Hotels Sultanahmet - Boutique Class',
    image: `${imageBase}/listing-bg-main-2.jpg`,
    imagesCount: 9,
    location: 'Kucukayasofya No. 40 Sultanahmet, Istanbul 34022',
    rating: 4.2,
    stars: 5,
    amenities: '20',
    price: 513,
    currency: '$',
    per: '/night',
    tax: 'excl. tax',
    reviews: 54,
    reviewLabel: 'Very Good',
  },
];
